Server/Server.Web/Areas/Admin/Models/Vendor/VendorModel.cs
using System;

namespace Phoenix.Server.Web.Areas.Admin.Models.Vendor
{
    public class VendorModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int? Logo { get; set; }

        public string Phone { get; set; }

        public string Nation { get; set; }

        public bool Deleted { get; set; }

        public DateTime CreateAt { get; set; }

        public DateTime? UpdatedAt { get; set; }
    }
}

Server/Server.Web/Areas/Admin/Controllers/VendorController.cs
using Falcon.Web.Core.Helpers;
using Falcon.Web.Framework.Kendoui;
using Phoenix.Server.Services.MainServices;
using Phoenix.Server.Web.Areas.Admin.Models.Vendor;
using Phoenix.Shared.Vendor;
using Phoenix.Server.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Phoenix.Server.Services.Database;
using Phoenix.Server.Web.Areas.Admin.Models.ImageRecord;

namespace Phoenix.Server.Web.Areas.Admin.Controllers
{
    public class VendorController : BaseController
    {
        // GET: Admin/Vendor
        private readonly IVendorService _vendorService;

        public VendorController(IVendorService vendorService)
        {
            _vendorService = vendorService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> List(DataSourceRequest command, VendorModel model)
        {
            var vendors = await _vendorService.GetAllVendors(new VendorRequest()
            {
                Page = command.Page - 1,
                PageSize = command.PageSize,
                Name = model.Name,
                Phone = model.Phone
            });

            var gridModel = new DataSourceResult
            {
                Data = vendors.Data,
                Total = vendors.DataCount
            };
            return Json(gridModel);
        }

        // Create Vendor
        public ActionResult Create()
        {
            var model = new VendorModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(VendorModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var vendors = await _vendorService.CreateVendors(new VendorRequest
            {
                Name = model.Name,
                Phone = model.Phone,
                Nation = model.Nation,
            });
            if (!vendors.Success)
            {
                ErrorNotification("Thêm mới không thành công");
                return View(model);
            }
            SuccessNotification("Thêm mới thành công");
            return RedirectToAction("Create");
        }

        #region Update
        public ActionResult Update(int id)
        {
            var projectDto = _vendorService.GetVendorsById(id);
            if (projectDto == null)
            {
                return RedirectToAction("List");
            }

            var projectModel = projectDto.MapTo<VendorModel>();
            return View(projectModel);
        }

        [HttpPost]
        public async Task<ActionResult> Update(VendorModel model)
        {
            var projetc = _vendorService.GetVendorsById(model.Id);
            if (projetc == null)
                return RedirectToAction("List");
            if (!ModelState.IsValid)
                return View(model);
            var vendors = await _vendorService.UpdateVendors(new VendorRequest
            {
                Id = model.Id,
                Name = model.Name,
                Phone = model.Phone,
                Logo = model.Logo,
                Nation = model.Nation,
                UpdatedAt = model.UpdatedAt,
            });
            SuccessNotification("Chỉnh sửa thông tin chương trình thành công");
            return RedirectToAction("Update", new { id = model.Id });
        }
        #endregion

        #region
        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var project = _vendorService.GetVendorsById(id);
            if (project == null)
                //No email account found with the specified id
                return RedirectToAction("Index");

            await _vendorService.DeleteVendors(project.Id);
            SuccessNotification("Xóa hãng sản xuất thành công");
            return RedirectToAction("Index");
        }
        #endregion










        // Add Hình Ảnh
        /*[Route("Create")]
        [HttpPost]
        public ActionResult Create(ImageRecordModel model)
        {
            HttpPostedFileBase file = Request.Files["ImageLogo"];
            ContentRepository service = new ContentRepository();
            int i = service.UploadImageInDataBase(file, model);
            if (i == 1)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }*/





        /* // Upload hình ảnh
         public class UploadOneFile
         {
             [Required(ErrorMessage = "Phai chon upload file")]
             [DataType(DataType.Upload)]
             [FileExtensions(Extensions = "pgn, jpg, jpeg, gif")]
             [Display(Name = "Chon upload file")]

             public IFromFile FileUpload { get; set; }
         }

         // Upload Image Vendor
         [HttpGet]
         public IActionResult UploadPhoto (int id)
         {
             // Lay ra san pham co id bang
             var vendors = _context.Vendor.Where(e => e.Id == id)
                 .Include(p => p.Photos)
                 .FirstOrDefault();

             if (vendors == null)
             {
                 return NotFound("Khong co hang san xuat");
             }

             ViewData["vendors"] = vendors;

             return View(); // Create View UploadPhoto, VendorModel -> Create Model VendorPhoto
         }

         // Upload hình ảnh
         [HttpPost, ActionName("UploadPhoto")]
         public async Task<IActionResult> UploadPhotoAsync (int id, [Bind("FileUpload")]UploadOneFile f)
         {
             // Lay ra san pham co id bang
             var vendors = _context.Vendor.Where(e => e.Id == id).FirstOrDefault();

             if (vendors == null)
             {
                 return NotFound("Khong co hang san xuat");
             }

             ViewData["vendors"] = vendors;

             if (f != null)
             {
                 var file1 = Path.GetFileNameWithoutExtension(Path.GetRandomFileName())
                     + Path.GetExtension(f.FileUpload.FileName);

                 var file = Path.Combine("Uploads", "thu muc: Products", file1);

                 using (var filestream = new FileStream(file, FileMode.Create))
                 {
                     await f.FileUpload.CopyToAsync(filestream);
                 }

                 _context.Add(new PhotoProduct() {
                     ProductId = product.ProductId,
                     fileName = file1
                 });

                 await _context.SaveChangesAsync();
             }

             return View(new UploadOneFile());
         }*/


    }
}

Server/Server.Web/Areas/Admin/Views/Vendor/Create.cshtml
@model Phoenix.Server.Web.Areas.Admin.Models.Vendor.VendorModel
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="intro-y flex flex-col sm:flex-row items-center mt-8">
        <h2 class="text-lg font-medium mr-auto">
            Thêm mới hãng sản xuất
        </h2>
        <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
            <a href="@Html.Raw(Url.Action("Index"))" class="btn btn-warning w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="corner-down-left" class="w-4 h-4 mr-2"></i> Quay lại
            </a>
            <button type="submit" class="btn btn-success w-32 mr-2 mb-2 flex items-center justify-center bg-theme-9 text-white">
                <i data-feather="save" class="w-4 h-4 mr-2"></i>Lưu
            </button>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

Server/Server.Web/Areas/Admin/Views/Vendor/Index.cshtml
@using Phoenix.Server.Services.Database;
@section Scripts{
    <script type="text/javascript" src="~/assets/js/tabulator.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
}
@section Breadcrumb{
    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <span>Chương trình</span> <i data-feather="chevron-right" class="breadcrumb__icon"></i>
        <a href="#" class="breadcrumb--active">Hãng sản xuất</a>
    </div>
}
@Html.AntiForgeryToken()
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Hãng sản xuất
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a href="@Url.Action("Create","Vendor")" class="btn btn-primary text-white shadow-md mr-2">Thêm mới</a>
    </div>
</div>
<div class="grid gap-6 mt-5">
    <div class="intro-y box p-5">
        <div class="grid grid-cols-12 gap-2">
            <div class="col-span-12 lg:col-span-6">
                <label>Nhà Sản Xuất</label>
                <input type="text" id="Name" class="form-control">     
            </div><div class="col-span-12 lg:col-span-6">
                <label>Số điện thoại</label>
                <input type="text" id="Phone" class="form-control">
            </div>
        </div>
        <div class="grid mt-3">
            <div class="w-full sm:w-auto flex mt-5 sm:mt-0 ml-auto">
                <button type="button" onclick="onResetSearch();" class="btn btn-danger text-white shadow-md mr-2">Xóa tìm kiếm</button>
                <button type="button" onclick="onSearch();" class="btn btn-success text-white shadow-md mr-2">Tìm kiếm</button>
            </div>
        </div>
    </div>
</div>
<div class="intro-y box p-5 mt-5">
    <div id="main-grid"></div>
    <script>
        var dateFormatter = function (cell, formatterParams) {
            var value = cell.getValue();

            if (value) {
                value = moment(value).format("DD/MM/YYYY HH:mm:ss");
            }

            return value;
        }
        var table = new Tabulator("#main-grid", {
            layout: "fitDataFill",
            ajaxURL: "@Html.Raw(Url.Action("List", "Vendor"))",
            ajaxConfig: "post",
            ajaxRequesting: function (url, params) {
                params.Name = $('#Name').val();
                params.Phone = $('#Phone').val();
            },
            ajaxResponse: function (url, params, response) {
                return response;
            },
            ajaxFiltering: true,
            paginationSize: 10,
            paginationSizeSelector: [10, 25, 50, 100],
            pagination: "remote",
            paginationDataSent: {
                "size": "pageSize",
                "page": "page",
            },
            paginationDataReceived: {
                "data": "Data",
                "last_page": "Total"
            },
            placeholder: "Chưa có dữ liệu",
            columns: [
                { title: "Id", field: "Id", sorter: "string", width: 100 },
                {
                    title: "Tên hãng sản xuất", field: "Name", sorter: "string", width: 200, formatter(cell, formatterParams)
                    {
                        return `<a href="../Admin/Vendor/Update/${cell.getData().Id}" class="text-theme-1 dark:text-theme-10"> ${cell.getData().Name}</a>`
                    }
                },
                {
                    title: "Số điện thoại", field: "Phone", sorter: "string", width: 180, formatter(cell, formatterParams) {
                        return `<a href="../Admin/Vendor/Update/${cell.getData().Id}" class="text-theme-1 dark:text-theme-10"> ${cell.getData().Phone}</a>`
                    }
                },
                {
                    title: "Ngày tạo", field: "CreatedAt", sorter: "date", width: 180, formatter: dateFormatter
                },
                {
                    title: "Ngày cập nhật", field: "UpdatedAt", sorter: "date", width: 180, formatter: dateFormatter
                },

                {
                    title: "", field: "Name", sorter: "string", width: 180, formatter(cell, formatterParams) {
                        return `<a href="../Admin/Vendor/Update/${cell.getData().Id}" class="btn btn-instagram text-white shadow-md mr-2"> Chỉnh sửa </a>`
                    }
                },
            ],
        });
        let onSearch = (e) => {
            table.setData();
        }
        let onResetSearch = (e) => {
            $('#Name').val('');
            $('#Phone').val('');
            table.setData();
        }
    </script>
</div>

Server/Server.Web/Areas/Admin/Views/Vendor/Update.cshtml
@model Phoenix.Server.Web.Areas.Admin.Models.Vendor.VendorModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="intro-y flex flex-col sm:flex-row items-center mt-8">
        <h2 class="text-lg font-medium mr-auto">
            @Model.Name
        </h2>
        <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
            <a href="@Html.Raw(Url.Action("Index"))" class="btn btn-warning w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="corner-down-left" class="w-4 h-4 mr-2"></i> Quay lại
            </a>
            <button type="submit" class="btn btn-success w-32 mr-2 mb-2 flex items-center justify-center bg-theme-9 text-white">
                <i data-feather="save" class="w-4 h-4 mr-2"></i>Lưu
            </button>
            <a href="javascript:;" data-toggle="modal" data-target="#delete-modal" class="btn btn-danger w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="trash" class="w-4 h-4 mr-2"></i> Xóa
            </a>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
<div class="modal" id="delete-modal">
    <div class="modal__content">
        <div class="p-5 text-center">
            <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Bạn có chắc chắn muốn xóa?</div>
            <div class="text-gray-600 mt-2">Do you really want to delete these records? This process cannot be undone.</div>
        </div>
        @using (Html.BeginForm("Delete", "Vendor", new { id = Model.Id }))
        {
            <div class="px-5 pb-8 text-center">
                <button type="button" data-dismiss="modal" class="btn btn-warning w-24 text-white mr-1">Không! Cám ơn.</button>
                <button type="submit" class="btn btn-success w-24 bg-theme-9 text-white">Đồng ý</button>
            </div>
        }
    </div>
</div>

Server/Server.Web/Areas/Admin/Views/Vendor/_CreateOrUpdate.cshtml
@using Falcon.Web.Mvc.HtmlExtensions
@model Phoenix.Server.Web.Areas.Admin.Models.Vendor.VendorModel
@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <div class="intro-y box p-5">
            <div>
                <label>Tên hãng sản xuất</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control input w-full border mt-2" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="mt-3">
                <label>Số điện thoại</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Quốc gia</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Nation, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    new TomSelect("#select-beast", {
        create: true,
        sortField: {
            field: "text",
            direction: "asc"
        }
    });
</script>