Server/Server.Web/Areas/Admin/Models/ProductSKU/ProductSKUModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Phoenix.Server.Web.Areas.Admin.Models.ProductSKU
{
    public class ProductSKUModel
    {
        public int Id { get; set; }

        public int Product_Id { get; set; }

        public double Price { get; set; }

        public double Rating { get; set; }

        public int BuyCount { get; set; }

        public string Screen { get; set; }

        public string OperationSystem { get; set; }

        public string Processor { get; set; }

        public string Ram { get; set; }

        public string Storage { get; set; }

        public string Battery { get; set; }

        public string BackCamera { get; set; }

        public string FrontCamera { get; set; }

        public string SimSlot { get; set; }

        public string GraphicCard { get; set; }

        public string ConnectionPort { get; set; }

        public string Design { get; set; }

        public string Size { get; set; }

        public int YearOfManufacture { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public bool Deleted { get; set; }
    }
}

Server/Server.Web/Areas/Admin/Controllers/ProductSKUController.cs
using Falcon.Web.Core.Helpers;
using Falcon.Web.Framework.Kendoui;
using Phoenix.Server.Services.Database;
using Phoenix.Server.Services.MainServices;
using Phoenix.Server.Web.Areas.Admin.Models.Product;
using Phoenix.Server.Web.Areas.Admin.Models.ProductSKU;
using Phoenix.Shared.ProductSKU;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Phoenix.Server.Web.Areas.Admin.Controllers
{
    public class ProductSKUController : BaseController
    {
        // GET: Admin/ProductSKU

        private readonly IProductSKUService _productSKUService;
        public ProductSKUController(IProductSKUService productSKUService)
        {
            _productSKUService = productSKUService;
        }

        #region
        public ActionResult Index(int id)
        {
            var model = new ProductSKUModel();
            model.Id = id;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(DataSourceRequest command, ProductSKUModel model)
        {
            var productSKUs = await _productSKUService.GetAllProductSKUById(model.Id, new ProductSKURequest()
            {
                Page = command.Page - 1,
                PageSize = command.PageSize,
                Product_Id = model.Product_Id,
                Ram = model.Ram,
                Deleted = false,
            });

            var gridModel = new DataSourceResult
            {
                Data = productSKUs.Data,
                Total = productSKUs.DataCount
            };
            return Json(gridModel);
        }

        public void SetViewBag(long? selected_Id = null)
        {
            DataContext db = new DataContext();

            ViewBag.Product_Id = new SelectList(db.Products.OrderBy(n => n.Name), "Id", "Name", selected_Id);
        }

        #endregion

        // Create ProductSKU
        public ActionResult Create()
        {
            SetViewBag();
            var model = new ProductSKUModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(ProductSKUModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var productSKUs = await _productSKUService.CreateProductSKUs(new ProductSKURequest
            {
                Product_Id = model.Product_Id,
                Price = model.Price,
                Rating = model.Rating,
                BuyCount = model.BuyCount,
                Screen = model.Screen,
                OperationSystem = model.OperationSystem,
                Processor = model.Processor,
                Ram = model.Ram,
                Storage = model.Storage,
                Battery = model.Battery,
                BackCamera = model.BackCamera,
                FrontCamera = model.FrontCamera,
                SimSlot = model.SimSlot,
                GraphicCard = model.GraphicCard,
                ConnectionPort = model.ConnectionPort,
                Design = model.Design,
                Size = model.Size,
                YearOfManufacture = model.YearOfManufacture,
            });
            if (!productSKUs.Success)
            {
                ErrorNotification("Lỗi");
                return View(model);
            }
            SuccessNotification("Thêm mới đại lý thành công");
            return RedirectToAction("Create");
        }

        // Update ProductSKU
        public ActionResult Update(int id)
        {
           
            var projectDto = _productSKUService.GetProductSKUById(id);
            
            DataContext db = new DataContext();

            ViewBag.Product_Id = new SelectList(db.Products.OrderBy(n => n.Name), "Id", "Name", projectDto.Product_Id);

            if (projectDto == null)
            {
                return RedirectToAction("List");
            }

            var projectModel = projectDto.MapTo<ProductSKUModel>();
            return View(projectModel);
        }

        [HttpPost]
        public async Task<ActionResult> Update(ProductSKUModel model)
        {
            var projetc = _productSKUService.GetProductSKUById(model.Id);

            DataContext db = new DataContext();

            ViewBag.Product_Id = new SelectList(db.Products.OrderBy(n => n.Name), "Id", "Name", projetc.Product_Id);

            if (projetc == null)
                return RedirectToAction("List");
            if (!ModelState.IsValid)
                return View(model);
            var productSKU = await _productSKUService.UpdateProductSKUs(new ProductSKURequest
            {
                Id = model.Id,
                Product_Id = model.Product_Id,
                Price = model.Price,
                // Rating = model.Rating,
                BuyCount = model.BuyCount,
                Screen = model.Screen,
                OperationSystem = model.OperationSystem,
                Processor = model.Processor,
                Ram = model.Ram,
                Storage = model.Storage,
                Battery = model.Battery,
                BackCamera = model.BackCamera,
                FrontCamera = model.FrontCamera,
                SimSlot = model.SimSlot,
                GraphicCard = model.GraphicCard,
                ConnectionPort = model.ConnectionPort,
                Design = model.Design,
                Size = model.Size,
                YearOfManufacture = model.YearOfManufacture,
            });
            SuccessNotification("Chỉnh sửa thông tin chương trình thành công");
            return RedirectToAction("Update", new { id = model.Id });
        }


        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var project = _productSKUService.GetProductSKUById(id);
            if (project == null)
                //No email account found with the specified id
                return RedirectToAction("List");

            await _productSKUService.DeleteProductSKUs(project.Id);
            SuccessNotification("Xóa đại lý thành công");
            return RedirectToAction("Index", "Product");
        }
    }
}

Server/Server.Web/Areas/Admin/Views/ProductSKU/Create.cshtml
@*Them chi tiet san pham*@
@model Phoenix.Server.Web.Areas.Admin.Models.ProductSKU.ProductSKUModel

@section Css {
    <link href="https://cdn.jsdelivr.net/npm/tom-select@1.7.5/dist/css/tom-select.css" rel="stylesheet">
}

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/tom-select@1.7.5/dist/js/tom-select.complete.min.js"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="intro-y flex flex-col sm:flex-row items-center mt-8">
        <h2 class="text-lg font-medium mr-auto">
            Thêm mới chi tiết sản phẩm
        </h2>
        <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
            <a href="@Html.Raw(Url.Action("Index", "Product"))" class="btn btn-warning w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="corner-down-left" class="w-4 h-4 mr-2"></i> Quay lại
            </a>
            <button type="submit" class="btn btn-success w-32 mr-2 mb-2 flex items-center justify-center bg-theme-9 text-white">
                <i data-feather="save" class="w-4 h-4 mr-2"></i>Lưu
            </button>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

Server/Server.Web/Areas/Admin/Views/ProductSKU/Index.cshtml
@using Phoenix.Server.Services.Database;
@section Scripts{
    <script type="text/javascript" src="~/assets/js/tabulator.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
}
@section Breadcrumb{
    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <span>Chương trình</span> <i data-feather="chevron-right" class="breadcrumb__icon"></i>
        <a href="#" class="breadcrumb--active">Chi tiết sản phẩm</a>
    </div>
}
@Html.AntiForgeryToken()
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Chi tiết sản phẩm
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a href="@Url.Action("Create","ProductSKU")" class="btn btn-primary text-white shadow-md mr-2">Thêm mới</a>
    </div>
</div>
<div class="grid gap-6 mt-5">
    <div class="intro-y box p-5">
        <div class="grid grid-cols-12 gap-2">
            <div class="col-span-12 lg:col-span-6">
                <label>Sản phẩm</label>
                <input type="text" id="NameProduct" class="form-control">
            </div>
        </div>
        <div class="grid mt-3">
            <div class="w-full sm:w-auto flex mt-5 sm:mt-0 ml-auto">
                <button type="button" onclick="onResetSearch();" class="btn btn-danger text-white shadow-md mr-2">Xóa tìm kiếm</button>
                <button type="button" onclick="onSearch();" class="btn btn-success text-white shadow-md mr-2">Tìm kiếm</button>
            </div>
        </div>
    </div>
</div>
<div class="intro-y box p-5 mt-5">
    <div id="main-grid"></div>
    <script>
        var dateFormatter = function (cell, formatterParams) {
            var value = cell.getValue();

            if (value) {
                value = moment(value).format("DD/MM/YYYY HH:mm:ss");
            }

            return value;
        }
        var table = new Tabulator("#main-grid", {
            layout: "fitDataFill",
            ajaxURL: "@Html.Raw(Url.Action("Index", "ProductSKU"))",
            ajaxConfig: "post",
            ajaxRequesting: function (url, params) {
                params.NameProduct = $('#NameProduct').val();
                params.Ram = $('#Ram').val();

            },
            ajaxResponse: function (url, params, response) {
                return response;
            },
            ajaxFiltering: true,
            paginationSize: 10,
            paginationSizeSelector: [10, 25, 50, 100],
            pagination: "remote",
            paginationDataSent: {
                "size": "pageSize",
                "page": "page",
            },
            paginationDataReceived: {
                "data": "Data",
                "last_page": "Total"
            },
            placeholder: "Chưa có dữ liệu",
            columns: [
                { title: "Id", field: "Id", sorter: "string", width: 100 },
                {
                    title: "Tên sản phẩm", field: "NameProduct", sorter: "string", width: 350, formatter(cell, formatterParams) {
                        return `<a href="../Update/${cell.getData().Id}" class="text-theme-1 dark:text-theme-10"> ${cell.getData().NameProduct}</a>`
                    }
                },
                { title: "Giá bán", field: "Price", sorter: "number", width: 180 },
                { title: "Chip xử lý", field: "Processor", sorter: "string", width: 180 },
                { title: "Ram", field: "Ram", sorter: "string", width: 180 },
                { title: "Bộ nhớ", field: "Storage", sorter: "string", width: 180 },
                {
                    title: "Ngày tạo", field: "CreatedAt", sorter: "date", width: 180, formatter: dateFormatter
                },
                {
                    title: "Ngày cập nhật", field: "UpdatedAt", sorter: "date", width: 180, formatter: dateFormatter
                },
                {
                    title: "", field: "", sorter: "string", width: 180, formatter(cell, formatterParams) {
                        return `<a href="http://localhost:63298/Admin/Warehouse/Index/${cell.getData().Id}" class="btn btn-instagram text-white shadow-md mr-2"> Xem số lượng </a>`
                    }
                },
                {
                    title: "", field: "", sorter: "string", width: 180, formatter(cell, formatterParams) {
                        return `<a href="../Update/${cell.getData().Id}" class="btn btn-instagram text-white shadow-md mr-2"> Chỉnh sửa </a>`
                    }
                },
            ],
        });
        let onSearch = (e) => {
            table.setData();
        }
        let onResetSearch = (e) => {
            $('#NameProduct').val('');
            table.setData();
        }
    </script>
</div>

Server/Server.Web/Areas/Admin/Views/ProductSKU/Update.cshtml
@model Phoenix.Server.Web.Areas.Admin.Models.ProductSKU.ProductSKUModel

@section Css {
    <link href="https://cdn.jsdelivr.net/npm/tom-select@1.7.5/dist/css/tom-select.css" rel="stylesheet">
}

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/tom-select@1.7.5/dist/js/tom-select.complete.min.js"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="intro-y flex flex-col sm:flex-row items-center mt-8">
        <h2 class="text-lg font-medium mr-auto">
            Chỉnh sửa chi tiết sản phẩm
        </h2>
        <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
            <a href="@Html.Raw(Url.Action("Index", "Product"))" class="btn btn-warning w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="corner-down-left" class="w-4 h-4 mr-2"></i> Quay lại
            </a>
            <button type="submit" class="btn btn-success w-32 mr-2 mb-2 flex items-center justify-center bg-theme-9 text-white">
                <i data-feather="save" class="w-4 h-4 mr-2"></i>Lưu
            </button>
            <a href="javascript:;" data-toggle="modal" data-target="#delete-modal" class="btn btn-danger w-32 mr-2 mb-2 flex items-center justify-center bg-theme-7 text-white">
                <i data-feather="trash" class="w-4 h-4 mr-2"></i> Xóa
            </a>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
<div class="modal" id="delete-modal">
    <div class="modal__content">
        <div class="p-5 text-center">
            <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Bạn có chắc chắn muốn xóa?</div>
            <div class="text-gray-600 mt-2">Do you really want to delete these records? This process cannot be undone.</div>
        </div>
        @using (Html.BeginForm("Delete", "ProductSKU", new { id = Model.Id }))
        {
            <div class="px-5 pb-8 text-center">
                <button type="button" data-dismiss="modal" class="btn btn-warning w-24 text-white mr-1">Không! Cám ơn.</button>
                <button type="submit" class="btn btn-success w-24 bg-theme-9 text-white">Đồng ý</button>
            </div>
        }
    </div>
</div>

Server/Server.Web/Areas/Admin/Views/ProductSKU/_CreateOrUpdate.cshtml
@using Falcon.Web.Mvc.HtmlExtensions
@model Phoenix.Server.Web.Areas.Admin.Models.ProductSKU.ProductSKUModel

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <div class="intro-y box p-5">
            <!--<div>
                <label>Tên sản phẩm</label>-->
            @*@Html.DropDownList("ProductType_Id", null, new { @class = "form-control input w-full border mt-2" })*@
            <!--<select id="selectProduct" name="Product_Id" class="tom-select"></select>
                <script>
                    var zsettings = {
                        valueField: 'Id',
                        labelField: 'Name',
                        searchField: 'Name',
                        placeholder: '-- Vui lòng chọn nhóm --',
                        load: function (query, callback) {
                            var url = '/api/dropdown/TakeAllProducts';
                            fetch(url, { method: "post" })
                                .then(response => response.json())
                                .then(json => {
                                    callback(json);
                                }).catch(() => {
                                    callback();
                                });

                        },
                        render: {
                            option: function (item, escape) {
                                return `<option value="${item.Id}"> ${item.Name} </option>`;
                            },
                            item: function (item, escape) {
                                return `<option value="${item.Id}"> ${item.Name} </option>`;
                            }
                        }
                    };
                    new TomSelect('#selectProduct', zsettings);
                </script>
            </div>-->

            <div>
                <label>Tên sản phẩm</label>
                @Html.DropDownList("Product_Id", null, new { @class = "form-control input w-full border mt-2" })
            </div>

            <div class="mt-3">
                <label>Giá bán</label>
                <input type="text" name="Price" value="@Model.Price" class="form-control" />
            </div>

            <div class="mt-3">
                <label>Màn hình</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Screen, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Hệ điều hành</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.OperationSystem, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Chip xử lý</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Processor, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Ram</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Ram, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Bộ nhớ</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Battery</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Battery, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Camera sau</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.BackCamera, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Camera trước</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.FrontCamera, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Sim</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.SimSlot, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Card đồ họa</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.GraphicCard, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Cổng kết nối</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.ConnectionPort, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Thiết kế</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Design, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Kích thước</label>
                <div class="mt-2">
                    @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control input input--switch border" } })
                </div>
            </div>

            <div class="mt-3">
                <label>Năm sản xuất</label>
                <input type="text" name="YearOfManufacture" value="@Model.YearOfManufacture" class="form-control" />
            </div>
        </div>
    </div>
</div>